Bouni/kicad-jlcpcb-tools

plugin.py

I think it is convenient in lot of cases to Toggle BOM & CPL at same time in one click so I have added that feature

Add "Toggle BOM/CPL" feature

---

library.py
partdetails.py

Sending User-Agent when downloading the CSV from JLCPCB.

---

fabrication.py

Fix for #107

---

helpers.py
mainwindow.py
partdetails.py
partselector.py
rotations.py

This PR add support for high DPI screens as requested in #110

High DPI support

---

.gitignore
README.md
fabrication.py
helpers.py
library.py
mainwindow.py
partselector.py
plugin.py
rotations.py
store.py

This PR is to update some spelling oversights as English can be a challenging language.

Fix some word spellings in the repo

---

library.py
mainwindow.py

Fix for #122

---

fabrication.py

Generate drill map files as requested in #125

Generate drill map files

---

fabrication.py

Forgot to include the drill map files to the ZIP, see #125

add drill map files to zip

---

mainwindow.py
rotations.py

Clear "Regex" value on list deselection to re-enable "Add" functionality

Added rotation offset column to component list

---

fabrication.py
helpers.py
mainwindow.py
store.py

Fix panalized pos files

---

mainwindow.py

Dispaly top/bottom info in parts list as requested in #142

Display Top/Bottom info in parts list

---

mainwindow.py
rotations.py

this with open the Rotation Manager with the footprint set as the Regex

Added Right Click "Add Rotation" menu option

---

partselector.py
settings.json

This PR  persists the checkboxes in the partselector as requested in #147.
Maybe this is the start for more settings that can be persisted ...

Persist checkboxes in partselector

---

fabrication.py

- Removed `popt.SetExcludeEdgeLayer(True)` to fix #157
- Changed `popt.SetSubtractMaskFromSilk(False)` to `popt.SetSubtractMaskFromSilk(True)` to fix #156

fix for #165 and #157

---

mainwindow.py
partdetails.py
partselector.py
rotations.py

Fixed SetBitmap error for Kicad 6.99

---

library.py
mainwindow.py
partdetails.py
settings.json

Remove all walrus operators in order to support older python versions

---

library.py
mainwindow.py
partmapper.py
rotations.py

Created a Footprint/Value to LCSC Partnumber "Mapping" database and dialog. Mapping can be saved and reused with new projects.

Added Footprint/Value to LCSC Partnumber "Mapping" database

---

helpers.py
mainwindow.py

Note: Not tested for wx.BitmapBundle

Convert wx.Bitmap to wx.Icon for DataViewIconText

---

helpers.py
mainwindow.py
partdetails.py
partmapper.py
partselector.py
rotations.py

Check wxWidgets version in order to decide wether to use Bitmap or BitmapBundle for button icons and static Icons.
Hopefully fixes #181 on all platforms 🤞🏽

Check wxWidgets version 

---

mainwindow.py
schematicexport.py

This was almost entirely done by @computergeek1507 but I messed up his PR #183. Shame on me :zany_face:

Added exporting LCSC property to KiCad v6 Schematic Files

---

README.md

This could be very useful for people new to KiCAD. It would have saved me a few minutes :)

Added info about how to run pluggin to READEME.md

---

schematicexport.py

skip symbol library part section, fix single digit XY positions, fix zero is a valid property ID, fix add/replace logic to prevent duplicate LCSC fields, added more logging, delete temp "old" files

schematic export fixes

---

library.py
partselector.py

This PR adds the ability to select the category and, optionally, subcategory from a dropdown list populated from the parts database. An example screenshot is shown below.

Support selecting category and subcategory from a ComboBox

---

README.md
fabrication.py
mainwindow.py

Changed the output folder to make handling of the files from JLCPCBs website easier.

Better output

---

helpers.py

Look for jlc as well as lcsc properties for the LCSC number

---

library.py

JLCPCB's CSV URL stopped working 5 days ago, and the plugin hasn't really had to handle this case so things can get weird. This fix attempts to work around and re-enable exporting and other features while we figure out a more long-term fix (better data source etc).
See #241 and #238 for more info
This is far from a comprehensive and well-tested "offline mode", but it gets the job done for me enough to export fab files, BOM, and POS files.  This could probably use a lot of testing.
future work:
- this could use some more UI polish to indicate better what's going on and what the consequences of that will be. for now it works as an emergency fix.
- pull using a cached data source (I have one, will try and work that into a future PR)

[emergency fix] attempt to allow startup even if we can't download the database

---

mainwindow.py

This PR allows you to add new rotation corrections via the right click menu in two ways, as before by package and new by name.

New rotation methods

---

helpers.py
mainwindow.py
partmapper.py
rotations.py

Up until now we looked for a key that contans `lcsc` but as mentionied by @karlp in #196 is way better to look for the value that starts with C followed by a number.

More flexible approach to get LCSC value

---

library.py

This PR will put rotations and mappings in their own databases so that they are no longer in the parts database as requested on #260 
When theses databases do not exist when the plugin is started, thery are created and rotations and mappings from the parts db are copied to the new databases. After that the tables are droped from the parts database.

Seperate rotations and mappings from parts db

---

.pre-commit-config.yaml
README.md

Start using pre-commit-hooks, for now only `Black`

Pre commit hooks

---

.github/workflows/linter.yml
.pre-commit-config.yaml
README.md
pyproject.toml

This adds isort, pylint, yamllint and pyupgrade

More pre-commit hooks

---

mainwindow.py

So this is an attempt to make the plugin work on Ubuntu as well as on OSx.

Do not add self.app if on OSx

---

fabrication.py

Add ZIP file compression

---

helpers.py

As reported in #326 the V7.99 nightlies introduced another breaking API change.
This PR handles old and new API.

Fix breaking API change in V7.99 nightly

---

.github/workflows/linter.yml
.github/workflows/update_parts_database.yml
jlcparts_db_convert.py

Metrics for db import that I added to help inform of things related to the fts5 changes but thought could be helpful separately.

jlcparts_db_convert.py metrics

---

helpers.py

Look for LCSC as well as JLC properties

---

jlcparts_db_convert.py

Introduce index on part number in parts DB during creation.

---

fabrication.py

Generate metric drill files instead of imperial

---

partselector.py

Tweak the column sizes and disable ellipsization to squeeze more in.

Column sizes

---

library.py
partselector.py

Move the stock column left a few spaces so it is visible by default.

Move stock

---

library.py

This changes the default behaviour to how it was previously (ie search all categories) but still allows category selection.

Add pseudo category 'All' and default to it.

---

.github/workflows/kicad-pcm.yml
.github/workflows/linter.yml
.github/workflows/update_parts_database.yml

I noticed a deprecation warning in the actions and therfore updated all used actions to their latest major version.

Update all used actions to the latest major version

---

.github/workflows/update_parts_database.yml

Hopefilly this will fix the delete artifact issue

Fix delete artifact in CI

---

fabrication.py

Alter the way the file extension is removed

Deal with filenames containing "."

---

.github/workflows/update_parts_database.yml

Use geekyeggo/delete-artifact@v4 instead of v4.1
Error message was `Error: Unable to resolve action 'GeekyEggo/delete-artifact@v4.1', unable to find version 'v4.1'`

Fix part db deploy step

---

README.md

Added formatting to allow click to copy of repository URL
Signed-off-by: Kelly Helmut Lord <kellyhlord@gmail.com>

readme: allow click to copy

---

jlcparts_db_convert.py

A few things found when rebuilding the fts5 db again.

Cmm jlcpcb script

---

__init__.py
__main__.py
fabrication.py
helpers.py
jlcparts_db_convert.py
library.py
partselector.py
schematicexport.py
standalone_impl.py
store.py
unzip_parts.py

KiCAD changed the API, unfortunately tented vias can no longer be set via the plugin in KiCAD 8.99, only via the layer setup of KiCAD.

Fix tented vias and aux_orgin correction for KiCAD 8.99

---

library.py
mainwindow.py

Show date and time when the last databse update was done in the titlebar

Show last update in title bar

---

fabrication.py

Possible fix for empty BOM file on KiCad 7 https://github.com/Bouni/kicad-jlcpcb-tools/issues/524
Explained here: https://github.com/Bouni/kicad-jlcpcb-tools/issues/535#issuecomment-2360655030

fix #524 empty BOM file on KiCad 7

---

library.py

- Implemented the feature to resume downloading the LCSC database to handle interrupted downloads
- Referenced Issue #536 and completed the required implementation

[feat] Add resuming download feature for LCSC database

---

partdetails.py

This fixes #570 as suggested by @markusdd

Fix part picture download

---

datamodel.py
library.py
partdetails.py
partselector.py

Use a DataViewCtrl instead of a DataViewListCtrl.
- better sorting
- Double Click selection of a part
- Datamodel in the background
These changes are approximately the smae as already done in the mainwindow a while ago

PartSelector refactoring

---

corrections.py
library.py
mainwindow.py

This PR fixes the logging issue descripbed in #623

Fix for logging issue
