Bouni/kicad-jlcpcb-tools

- fabrication.py
This allows having parts in BOM/CPL that have no LCSC property for automatic completion from JLC's webservice as requestet in #65 by @t123yh
> Allow missing LCSC property in BOM/CPL, fix for #65

- fabrication.py
Generate fabricate files will stop at half **silently** if there are non-ASCII characters in footprint's fields. Using utf-8 encoding for CPL and BOM file seems to settle this problem. BTW, It would be better if we print a log when something went wrong.
> Use utf-8 encoding for BOM and CPL file

- fabrication.py
Added solder paste to fabrication data for stencil.
JLCPCB require solder paste layer for zipped fabrication file. 
https://support.jlcpcb.com/article/149-how-to-generate-gerber-and-drill-files-in-kicad
p.s
Thank you for making great extension!
> Added solder paste to fabrication data

- mainwindow.py
- partdetails.py
- partselector.py
- rotations.py
There is a problem with the AcceleratorTable in recent KiCad versions on Linux.
With these changes it works on Linux as well as on Windows 10.
OSX still needs testing, @DanielO would you mind helping me aut with a OSX test, please?
> Potential fix for #87

- fabrication.py
Before this change, parts that have a description containing non-ascii symbols, such as a +- or a µ would cause writing of the .pos file to silently fail.
> Write the POS file as utf8

- library.py
- mainwindow.py
This triggers a download of the parts database if it is not already present.
It also prevents the population of the footprint list which need that library.
The population is done at the end of the download anyway which results in an empty footprint list for the duration of the download.
> Fix for #111

- helpers.py
- mainwindow.py
- partdetails.py
- partselector.py
- rotations.py
This is a hacky attempt to fix #118.
It seems linux versions of KiCAD use wxWidgets 3.0.4 while Windows uses 3.1.5.
In order to support HighDPI Displays I introduced the use of the FromDIP method which, unfortunately is supported from wxWidgets 3.1.0 onwards.
This means that at the moment there's no High DPI support for linux after this PR has been merged but at least the plugin is usable again in linux.
> Attempt to fix wxWidgets < 3.1 issue with HighDPI capabilities

- .gitignore
- fabrication.py
- mainwindow.py
I have seen a nasty crash of Kicad when multiple rows are selected and then the "Select Alike" button is pressed. Now the code just reports that you need to select only one row.
> Handle part select function when multiple rows are selected (no crash anymore)

- fabrication.py
Parts marked as "exclude from POS" ended up in the POS file. Fixed with this PR.
> Bugfix: prevent non POS parts from ending up in POS file

- fabrication.py
The KiKit panelize plugin export the V cut marking into the User.Comments layer by default. JLCPCB support custom V scoring specified by the end-user just it needs to be exported in own gerber file and mentioned in the job comment.
> Export User.Comments layer as a V-score layer

- mainwindow.py
- partselector.py
Finally I found a working solution for #165.
I had to change the call from `dialog.Show()` into `dialog.ShowModal()` in order to resolve the issue.
Maybe not optimal but I wasn't able to figure out another way 🤷🏽
> Fix for #165 by making part details dialog a modal

- helpers.py
- mainwindow.py
- partdetails.py
- partmapper.py
- partselector.py
- rotations.py
Up until now 6.0version needed a different handling of icons than 6.99 versions.
That broke with 6.0.6, which now needs the same treatment as 6.99.
I used that chance to refactor said handling a bit.
> Refactor loading of scaled icons

- partdetails.py
This is a fix for #190, the `static=True` got missing in one of the last changes for the Bitmap/BitmapBundle mess ...
> Fix loading of static bitmap in partdetails

- fabrication.py
As suggested by @Jan21493 in #194 taking the Aux Oriin into account when generating the POS file should fix position offsets for those who changed their KiCAD Grid origin settings 🚀
> Take AuxOrigin into accout when generating POS file

- partdetails.py
1. exception fix: self.EndModal() requires a return value to be passed in
2. refactor duplicated error message handler to drop some better hints about how to fix issues with incorrect or missing LCSC part#s
> improve error handling in PartsDetail modal dialog box

- schematicexport.py
The condition was inverted and prevented from finding the part in the store. Inverting it makes the export work
> Fix schematic export

- fabrication.py
When Aux origin is set, generated drill files don't match gerbers and position files. This inconsistency happens due to offset calculation. Gerbers and position files use Aux origin for offset, while drill files use fixed (0, 0) for all cases.
This can be easily seen on the screenshot (aux origin is set to lower left corner of the PCB):
The pull-request makes offset for drill files identical to gerbers and position files.
> Offset drill file to Aux origin to match other fabrication files

- fabrication.py
See also issue #159
This fixes the rotation of parts on the bottom/back layer. Some(!) testing has been done.
One possible issue could be existing projects where the rotation correction feature of the plugin has been used for bottom parts. Those correction values will now most likely be incorrect. I am not sure if an automatic correction of those values is possible or even desireable; in my (limited) testing it was easiest to delete all corrections and start again...
> [Fix] Bottom rotation angle

- fabrication.py
- mainwindow.py
KiCAD refers to the placment as POS where JLC uses CPL. At least the filename should match JLCs used term to make it clearer.
> Rename output placement file to CPL instead of POS

- mainwindow.py
Footprints with names like Connector(2-pin) will generate regexes that don't actually match the footprint name when you click "Add Rotation". This fixes that by escaping the special characters, at least for the connector in my layout.
> escape footprint names when using them to make a regex

- library.py
see #241 for impetus, URL is 404'ing.
this PR does nothing but just shows the URL so maintainers can better figure out what's going on from (what is sure to be) a bunch of incoming bug reports for the same thing in the near future. it's optional
see also: #242
> [cosmetic] UX: improve error msg if JLC URL fails to download

- library.py
As long as JLCPCB doesn't com up with a new way to download their parts catalog we download the last state from 2022-11-23 and use that.
> Replace JLCPCB CSV download with Fallback sqlite db download

- library.py
Renaimg parts.db is not possible if the parts.db.bak file already exists. If so, delte the already existing bak file
> Fix for renaming issue

- events.py
- mainwindow.py
- partselector.py
Small improvement that fixes long freezes caused by running method `populate_footprint_list` for every assigned part.
> Make part selector assign multiple parts at once

- fabrication.py
Fix for another API change in 6.99.
`PCB_PLOT_PARAMS.NO_DRILL_SHAPE` became `DRILL_MARKS_NO_DRILL_SHAPE`
> Fix drill marks exception in 6.99

- fabrication.py
- mainwindow.py
If the part name matches the regex that correction will be applied, if that is not the case the package is checked and that correction applied if the regex matches.
This allows for more specific rotation corections as for example not all `SOT-23-5` need the same rotation.
> Allow rotation corrections based on part name

- fabrication.py
- helpers.py
As Version 7.0 was released recently, the handling of differences in the KiCAD API in some places is broken because we only checked for 6.99. This adds 7.0 as nightly version ...
> Fix check for nightly versions

- fabrication.py
JLC position parser is expecting the center of the component, Use bounding box to determine component center. Mostly effects through holes as their position is normally pin 1 not center
> Use bounding box to determine component position center

- helpers.py
As mentioned in #289 by @Trajelectory currently nightly versions aka 7.99 are not recognized.
> Fix for #289

- fabrication.py
https://github.com/Bouni/kicad-jlcpcb-tools/issues/294
For some reason, my 6.0.4 KiCAD is returning an object, not a float, even though that supposedly was only added in 6.99.  This PR removes the assumption that the change is based on version, and instead just tries the new way, and falls back to the old way if it's not available yet.
> Restore orientation compatibility between various KiCAD versions

- .github/workflows/update_parts_database.yml
- .gitignore
- jlcparts_db_convert.py
- unzip_parts.py
Work in progress to resolve #304
Strategy: fetch jlcparts database which is generated daily, convert it to this plugins format to bring down size and enhance usability for the purposes of this plugin.
A github pipeline should then run daily, always serving the latest db, tehn just the download function of this plugin needs adaptation.
- [x split zip in pure python so that it can be reassembled, Github limits to 100MB file size
> add script to convert jlcparts db to plugin style db

- .github/workflows/update_parts_database.yml
Its completely useless to have the update parts database action running on each push / pull request.
> Only run Update parts database on schedule

- const.py
- helpers.py
- mainwindow.py
This allows much faster toggling of BOM / POS values without re-populating the entire list.
Should also help with list jump to position 0
> Toggle BOM/POS without re-populate entire list

- helpers.py
Capacitors are named C1 for example and that was falsely taken as the LCSC number.
> Look for "lcsc" in key and then for C number in value

- helpers.py
As reported in #330 and #353 on Mac OS a scale factor of 1.0 is needed in order to scale the icons correctly.
> Force Scalefactor to 1.0 if on Mac OS

- helpers.py
Tested on MacOS 13.4 and current KiCAD 7.
Had to patch the scaling to 1.0 as well, BTW (Bouni#330).
Great plugin!
> Fix icon colours for dark theme

- helpers.py
Reverts Bouni/kicad-jlcpcb-tools#353
Unfortunately it seems that my windows settings are set to Dark mode but the wx frames of the plugin are still light.
That means the icons become white and are nearly invisible ☹️
> Revert "Fix icon colours for dark theme"

- helpers.py
Fixes #362, where a crash happens on startup for certain versions of wx that do not have `GetAppearance` and `IsUsingDarkBackground` attributes. This issue is only present in stable version  `2023.08.02`.
This fix checks for the existence of the attributes before checking their contents.
> Added wx attributes check to prevent startup crash

- mainwindow.py
It was pointed out by a KiCAD developer that the `self.app = wx.App()` might be the problem. See [issue 15520](https://gitlab.com/kicad/code/kicad/-/issues/15520) for details.
Removing it solved the issue for me but most likely will bring back #291
So I looked at KiBuzzards source an shamelessly stole [two lines](https://github.com/gregdavill/KiBuzzard/blob/main/KiBuzzard/__init__.py#L33-L34) from there 😅
> Possible fix for Plugin Crash

- README.md
I noticed that the Development section mentioned `pre-commit install` instead of `pre-commit run`, which I believe is a mistake.
Added a few more small nits
> docs: Slightly spruce up README.md

- fabrication.py
Solves issue https://github.com/Bouni/kicad-jlcpcb-tools/issues/379 that silkscreen was affecting centroid position calculation.
Nice and center now regardless of the uneven silk:
> Calculate footprint centroid based on its pads.

- fabrication.py
- helpers.py
- mainwindow.py
I'm not sure if the get_footprint_by_ref() is necessary for older versions of kicad but that could be a good reason to keep it.
The direct calls make it easier to determine which object is being referenced.
> Cmm direct - Direct calls and remove duplicate helper

- fabrication.py
This fixes the problem that shows up relatively rare. #374 - That is it fixes rotation for parts that require rotation and are placed on top and bottom assembly.
> Rotation correction bottom assembly

- library.py
I was getting error messages when generating files because `Fabrication.rotate()` was trying to use rotations as numbers but they were really coming out of the database as strings. This parses the values coming from the database as integers.
> Load rotations from database as ints

- partdetails.py
attributes use capital spelling and also the existing hardcoded params were inconsistent. harmonized everything to capital spelling and added assembly process param (which is THT or SMT), which I think is actually pretty useful
> harmonize spelling and add assembly process param

- .github/workflows/update_parts_database.yml
The update_parts_database CI job started to fail a few days ago.
Thats caused by an increased number of volumes in the split cache.zip.
> Fix CI, number of volumes has increased

- rotations.py
Remove inactive wx.ALIGN_CENTER_VERTICAL flags on elem…ents inside of vertical BoxSizers
The flag produces an assertion error as only horizontal alignment is possible inside of vertical sizers.
Assertion output:
Traceback (most recent call last):
File "/Users/cmorgan/Documents/KiCad/8.0/scripting/plugins/kicad-jlcpcb-tools/mainwindow.py", line 883, in manage_rotations
RotationManagerDialog(self, "").ShowModal()
File "/Users/cmorgan/Documents/KiCad/8.0/scripting/plugins/kicad-jlcpcb-tools/rotations.py", line 89, in __init__
sizer_right.Add(correction_label, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5)
wx._core.wxAssertionError: C++ assertion "CheckSizerFlags(!((flags) & (wxALIGN_CENTRE_VERTICAL)))" failed at ./src/common/sizer.cpp(2273) in DoInsert(): wxALIGN_CENTRE_VERTICAL will be ignored in …
> rotations.py - Cleanup BoxSizer flags

- README.md
- __init__.py
- __main__.py
- fabrication.py
- mainwindow.py
- standalone_impl.py
- store.py
Bringing this one back since it was helpful in debugging plugin changes that were resulting in crashes.
- motivation: I wanted to be able to debug the UI with PyCharm/vscode
- this is not the most stable thing in the world but gets the job done
- allows the UI to start without Kicad being started, which allows real debugging from an IDE
- see __main__.py for instructions on how to launch this
- wrap all calls to GetBoard() with a class that can return a fake stub
> add new standalone mode for startup

- mainwindow.py
This patch corrects an issue where the rotation data was not being displayed correctly in the UI due to type recognition problems with the wx framework. Previously, certain rotation correction values were not converted to strings before adding to a wx list, leading to them being ignored by the GUI framework, showing no data and not reporting any errors.
The fix involves explicit string conversion of the rotation data in the populate_footprint_list method. Specifically, when correction rules are applied based on part names or packages, the corrected rotation values (part[8]) are now converted to strings (str(correction)) before being set. This change ensures that the wx framework recognises and displays the data correctly.
Please refer to this picture:
> Fix missing rotation corrections display in the main view

- README.md
- library.py
Fixed instructions in the readme that said to "Fit clone" a repo to "Git clone" and fixed the spelling of "spurious" in the library.py file.
> Frightrisk fix spelling

- fabrication.py
> Panel support

- fabrication.py
This reverts the changes made to the BOM creation in order to fix #481 
The fixed version now works for Panels as well as single PCBs
> Revert changes made to BOM creation in #480

- fabrication.py
This is an attempt to fix #484 
I cannot reporduce this issue but I think that a part is not found in the database which results in a None returned and that leads to a failed BOM creation
> Do not fail creating BOM if part is not found in database

- mainwindow.py
> Scale right hand toolbar according to DPI settings

- library.py
Sorting by Stock wasn't working because the column order was not right.
> Fix #466: Sort by stock in part selector

- partdetails.py
I've added a "Download datasheet" button to the part details modal:
This downloads the datasheet to `<project_path>/datahseets`
Fixes #384
> Add download datasheet button to partdetails

- .github/workflows/update_parts_database.yml
This fixes the broken update process due to [running out of disk space](https://github.com/Bouni/kicad-jlcpcb-tools/actions/runs/9902662267):
- install the requirements first
- then [maximize disk space](https://github.com/easimon/maximize-build-space?tab=readme-ov-file#usage) (remove optionally installed, and unused things - e.g. mono, merge tmp space)
- checkout as normal
In my fork this [passed as far as I have credentials](https://github.com/ukd1/kicad-jlcpcb-tools/actions/runs/9911850526/job/27385394133)...but I can't completely test. 
Note:
- there are [more things that can be dropped](https://github.com/easimon/maximize-build-space?tab=readme-ov-file#inputs), but this seems like enough
- this is somewhat temporary, if the disk usage goes over again
> Fix broken update process

- library.py
Before this function took about 5 seconds for my modest 51 line BOM. Now it takes 0.05s :sunglasses:
> make get_part_details 2500x faster

- fabrication.py
- helpers.py
- mainwindow.py
- store.py
I always struggled with al those index numbers scatterd all around the code base and for a long time wanted to improve that.
So I started with the store and introduced a [row_factory](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.row_factory) that returns a dict instead of a list which improves readability throughout the code base a lot.
For example
`if self.hide_bom_parts and part[6]:`
becomes
`if self.hide_bom_parts and part["exclude_from_bom"]:`
> Use dict_factory in store for better readability

- partselector.py
As requested ages ago in #66 I added two button which allow to easily add the Omega and the Micro symbol to the search string.
> Add buttons to easy add  Ω and µ to the search string. Fix for #66

- lcsc_api.py
- partdetails.py
With this change the LCSC API can be used in other parts of the code and its a lot cleaner overall.
> Refactor LCSC API into seperate class

- schematicexport.py
Recursively proceses hierarchical sheets when rewriting schematics files.
> Adds support for hierarchical sheets when rewriting schematics files.

- library.py
- mainwindow.py
This makes the use of the result of get_part_details much clearer.
> Use dict_factory for get_part_details

- library.py
- mainwindow.py
PR #503 made the plugin way faster but introduced a problem so that no more part details are returned.
The main issue is (as far as may SQLite knowledge goes) that the named parameter was used in a wrong way.
The for loop gernerates a query like this for example, which does not yield any results:
`'''SELECT "LCSC Part", "Stock", "Library Type" FROM parts WHERE parts MATCH "LCSC Part:C2286"'''` 
Fixing that we end up with:
`'''SELECT "LCSC Part", "Stock", "Library Type" FROM parts WHERE parts MATCH C2286'''`
But that return every LCSC number that includes the searched number.
So limit the reults to 1 like this:
`'''SELECT "LCSC Part", "Stock", "Library Type" FROM parts WHERE parts MATCH C2286 LIMIT 1'''`
Gives us just the first match, which should give us the search LCSC number only.
I'm …
> Refactor populate_footprints and get_part_details

- partselector.py
This is an attempt to make the messy price column more useful.
We now go through the price ranges and check for the number of selected parts (doable via the alike button fr example) in whch price range we are. Then return that as the price:
> WIP: Show the price for the number of selected parts

- .github/workflows/linter.yml
- .pre-commit-config.yaml
- use ruff action instead of installing manually
- set ruff version to be consistent with pre-commit-config
- update versions
- let ruff fix fixable issues
- add ruff format
- let pyupgrade do its magic
> Update pre-commit-config and linter action

- .github/workflows/linter.yml
- .pre-commit-config.yaml
- datamodel.py
- helpers.py
- library.py
- mainwindow.py
- plugin.py
- store.py
I was aware that there are a lot of unused fuctions and vataibles throughout the code.
So I used [deadcode](https://github.com/albertas/deadcode) to find all unused functions and remove them.
In places where we overload functions I added `# noqa` comments
> Eliminate all dead code

- lcsc_api.py
- store.py
Could using unions instead of the | operator be a compromise to keep the compatibility with python 3.9 on macOS?
https://docs.python.org/3.10/library/typing.html#typing.Union
> Probable fix for #535 - use union instead of | operator for python 3.9 compatibility

- fabrication.py
Added quantity column to the BOM CSV output for each component. This lets us choose Quantity as one of the row headers in LCSCs BOM tool. The LCSC BOM tool now can allocate the correct quantity of parts for each part number
> Fixes #528 Feature/component count

- helpers.py
Fixes #546
The Python scripting API is a bit awkward.  It would be nice if `pcbnew.FOOTPRINT.SetField` returned the resulting field so we could call `SetVisible(False)` on it.
I looked for ways to bypass the call to `GetFieldByName()`.  The [source code for SetField](https://docs.kicad.org/doxygen-python-8.0/pcbnew_8py_source.html#l19337) has some ideas.  But it wasn't working quite right and I would have to modify the function signature to take `pcbnew` as an argument for use in standalone mode.  I think we would also have to modify our standalone impl to add a couple of extra stub methods.  
Thanks @Carbon225 for the example code showing the problem and a prototype solution.
> Fix LCSC numbers appearing on silkscreen

- mainwindow.py
> placehoDLer -> placehoLDer

- mainwindow.py
When empty board is used, `pcbnew.GetBoard().GetFileName()` returns `FileNotFound` exception which was not handled in `check_order_number` function. Catch `OSError` exception which should fix this behaviour.
Maybe longing an error would be useful?
> Fix: check_order_number function on empty files

- datamodel.py
- derive_params.py
- library.py
- mainwindow.py
- partdetails.py
- partselector.py
- settings.json
- standalone_impl.py
- store.py
There are several commits in this PR, sorry. However, they are all independent, so you can apply whichever you approve of.
They're all small conveniences except the "**Show parameters derived from LCSC description**" commit, which addresses the following pain points:
1. LCSC often buries the most important data (like the resistance of a resistor) at the end of the description field. For example: "50mW Thick Film Resistors ±200ppm/℃ ±1% 234kΩ". The "234kΩ" is past the point where the part details dialog truncates the description. (And that dialog is not resizable, which is one of the minor fixes.)
2. When choosing a part, the values aren't visible in the list. If you search for "5kΩ" you'll also get "25kΩ", "1.5kΩ", etc. and you can't see which is which without opening the details dialog. …
> Show component values in list (+ other minor conveniences)

- library.py
- unzip_parts.py
On top of @Oliver0804 s recent PR I thought having progress info for the zip deflation would be a nice thing to have.
> Add progress bar and logg messages to zip deflation

- mainwindow.py
Not a proper fix, but I have no time to investigate UnicodeDecodeErrors errors now.
Maybe later 🤷🏽‍♂️ 
This should at least prevent the plugin from crashing
> Catch UnicodeDecodeError in JLC order number check

- fabrication.py
As described in #563, JLC does not like Paste Layers nor V-Score layers in the ZIP file.
> Remove Paste and V-Score layers from ZIP file

- jlcparts_db_convert.py
The 'rotation' table in the parts database is created but I cannot find any usage of it.
So I removed it.
> Removed unused 'rotation' table from the parts database.

- helpers.py
- schematicexport.py
- Invert the version logic. Try to search for versions 6 and 7 explicitly. For versions 8+ use the default mechanism. This will allow us to be compatible with newly builds.
> refactor(schematic,version): refactor version handling

- corrections.py
- fabrication.py
- jlcparts_db_convert.py
- library.py
- mainwindow.py
Implements/Fixes #418
Renamed the rotations.db file to corrections.db to reflect the more general correction approach.
Implemented update logic to convert existing rotation databases to the new correction database (setting the offsets to 0 in this case).
The online corrections file already contains offsets, these are imported.
Some notes about things I am unsure about:
* While implementing this, I noticed that there is a `rotation` table created in the parts.db. This table seems to be never used thus I removed the table creation. (see change of jlcparts_db_convert.py)
* I’m not 100% sure if the code works with KiCAD before version 8, I especially unsure if the usage of wxPoint in fabrication.py is the correct way to do what I do there.
* The new code automatically imports the previous …
> Extended rotation correction to also have X/Y offsets.

- corrections.py
I noticed that e.g. setting a rotation of '90x' resulted in a unreadable correction table.
(No issue to link this pull request to because I already have the fix …)
Please review the code, I am not sure if it matches your code style.
I tried my best but python still is not my main language.
> Added some input sanitization to prevent database corruption.

- corrections.py
- library.py
Based on my other pull request (#583), I added an option to use project local corrections: By default the global corrections database is used but you can choose to use project local corrections. When doing so, the then current global corrections are copied into the project.db database and that data is used.
Returning to the global corrections database simply drops the correction table from the project.db (with an appropriate warning since all local corrections are lost).
The logic whether the local or global correction data is used is based on the existence of the correction table in project.db. If it exists, even empty, local correction data is used, if it does not exist, global correction data is used.
If you want to transfer the local corrections into the global corrections database, …
> Board local corrections

- .github/workflows/update_parts_database.yml
This is a fix for #612 
We already use `ubuntu-latest` in all the other GH actions, so I chaged `update_parts_database.yml` to use it as well.
> Fix broken update parts database action

- mainwindow.py
- settings.py
No longer checking for text marker occurance anywhere in the file but checking text elements. Also checking for serial number (2D barcode) placeholders.
If more than one placeholder is detected, a warning is shown.
> Improved order number placeholder check.

- fabrication.py
- mainwindow.py
Fix for issue #602:
* Unified correction matching between main window and fabrication, new order is reference, value, footprint.
* Added an indicator (“(ref)”, ”(val)”, “(fpt)“) to the correction column to show what the correction matched on.
Also includes pull #477 (Added rotation by reference):
* Added context menu item to create correction rule based on reference.
Additionally:
* Changed column title “Value” to “Value (Name)” since value is sometimes called name in the UI elsewhere.
> Unified correction matching between main window and fabrication.

- mainwindow.py
The latest changes introduced a bug that prevents the plugin from being closed.
Fixes #627
> Catch exception when trying to remove logging handlers on Plugin close

- core/version.py
Versions like `9.0.2-2.fc42` or `7.0.0-rc1-378-ge76fd128c3` were causing an errors, so they have to be normalised before comparison.
/cc @slabua
> fix(version): make version checking more robust

- corrections.py
The following rules are used when saving:
* Nothing selected, new regex 
Add a new entry.
* Nothing selected, regex exists, all values equal
Select row.
* Nothing selected, regex exists, values differ
Ask user if entry should be updated.
* The selected regex is equal to the edit field
Update the entry.
* The selected regex is different from the edited one but new
Update entry (changing the regex).
* The selected regex is different from the edited one but other row for that regex exists
Ask the user if that entry should be replaced.
That means the selected entry is deleted, the existing one is updated.
Please note that I changed the correction list selection mode from single row to multiple rows (but unselect all but one row in the selection handler). I did this because I did not find any …
> Added handling of duplicate entries on saving a correction.

- helpers.py
Allow `-` but limit length to 8 in order to ignore kibuzzard footprints
> Fix for regex for valid part references 

- PCM/create_pcm_archive.sh
The `version.py` file was missing as same as the own python packaging module from `lib` folder.
> fix(release): copy missing files into release archive
